CREATE TABLE test1 
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	code INT,
	PRIMARY KEY (id)
) COMMENT 'тестовая ООП',
ENGINE=InnoDB;


CREATE TABLE results 
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	с1 VARCHAR(50) NOT NULL DEFAULT '',
	с2 VARCHAR(50) NOT NULL DEFAULT '',
	result INT DEFAULT NULL,
	tour INT NOT NULL,
	date DATE NOT NULL,
	PRIMARY KEY (id)
) COMMENT 'таблица результатов матчей',
ENGINE=InnoDB;

DROP TABLE IF EXISTS rt1;

CREATE TABLE rt1
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	t1 VARCHAR(20) NOT NULL DEFAULT '',
	t2 VARCHAR(20) NOT NULL DEFAULT '',
	g1 INT DEFAULT NULL,
	g2 INT DEFAULT NULL,
	date DATE NOT NULL,
	PRIMARY KEY (id)
) COMMENT 'Таблица результатов матчей первого тура',
ENGINE=InnoDB;


DROP TABLE IF EXISTS results;
DROP TABLE IF EXISTS results_temp;
CREATE TABLE results_temp
CREATE TABLE results
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	t1 VARCHAR(20) NOT NULL DEFAULT '',
	t2 VARCHAR(20) NOT NULL DEFAULT '',
	g1 INT DEFAULT NULL,
	g2 INT DEFAULT NULL,
	tour INT NOT NULL,
	date DATE NOT NULL,
	PRIMARY KEY (id)
) COMMENT 'Таблица результатов матчей',
ENGINE=InnoDB;

DROP TABLE IF EXISTS res;
CREATE TABLE res
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	t1 VARCHAR(3) NOT NULL DEFAULT '',
	t2 VARCHAR(3) NOT NULL DEFAULT '',
	g1 INT DEFAULT NULL,
	g2 INT DEFAULT NULL,
	tour INT NOT NULL,
	date DATE NOT NULL,
	PRIMARY KEY (id)
) COMMENT 'Таблица результатов матчей',
ENGINE=InnoDB;

DROP TABLE IF EXISTS pl;

CREATE TABLE pl
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL DEFAULT 'comand',
	code VARCHAR(20) NOT NULL DEFAULT 'cmnd',
	plays INT NOT NULL DEFAULT '0',
	wins INT NOT NULL DEFAULT '0',
	nich INT NOT NULL DEFAULT '0',
	lose INT NOT NULL DEFAULT '0',
	goals_out INT NOT NULL DEFAULT '0',
	goals_in INT NOT NULL DEFAULT '0',
	goals_res INT NOT NULL DEFAULT '0',
	points INT NOT NULL DEFAULT '0',
	PRIMARY KEY (id)
) COMMENT 'Итоговая турнирная таблица Английской премьер-лиги',
ENGINE=InnoDB;

DROP TABLE IF EXISTS apl;
DROP TABLE IF EXISTS apl_temp;
CREATE TABLE apl
CREATE TABLE apl_temp
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL DEFAULT 'comand',
	plays INT NOT NULL DEFAULT '0',
	wins INT NOT NULL DEFAULT '0',
	nich INT NOT NULL DEFAULT '0',
	lose INT NOT NULL DEFAULT '0',
	goals_out INT NOT NULL DEFAULT '0',
	goals_in INT NOT NULL DEFAULT '0',
	goals_res INT NOT NULL DEFAULT '0',
	points INT NOT NULL DEFAULT '0',
	PRIMARY KEY (id)
) COMMENT 'Итоговая турнирная таблица Английской премьер-лиги',
ENGINE=InnoDB;